export const HELLO_WORLD = 'HELLO_WORLD';

export const SEARCH_PROFILES_SUCCESS = 'SEARCH_PROFILES_SUCCESS'
export const SEARCH_PROFILES_ERROR = 'SEARCH_PROFILES_ERROR'

export const SEARCHBAR_GENDER_SELECTED = 'SEARCHBAR_GENDER_SELECTED';
export const SEARCHBAR_SERVICE_SELECTED ='SEARCHBAR_SERVICE_SELECTED';
export const SEARCHBAR_ORIENTAION_SELECTED ='SEARCHBAR_ORIENTAION_SELECTED';

export const AWAPI_GETGENDERS_SUCCESS = 'AWAPI_GETGENDERS_SUCCESS';
export const AWAPI_GETGENDERS_ERROR = 'AWAPI_GETGENDERS_ERROR';

export const AWAPI_GETORIENTATIONS_SUCCESS = 'AWAPI_GETORIENTATIONS_SUCCESS';
export const AWAPI_GETORIENTATIONS_ERROR = 'AWAPI_GETORIENTATIONS_ERROR';
